name: Docker Build and Push

on:
  workflow_run:
    workflows: ["SemVer Tag"]
    types:
      - completed

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set image tags
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          echo "IMAGE_NAME=${{ secrets.DOCKER_HUB_USER }}/reservium-ui" >> $GITHUB_ENV
          echo "VERSION_LATEST=latest" >> $GITHUB_ENV
          echo "VERSION_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg VITE_GOOGLE_CALENDAR_API_KEY=${{ secrets.VITE_GOOGLE_CALENDAR_API_KEY }} \
            --build-arg VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }} \
            -t $IMAGE_NAME:$VERSION_LATEST \
            -t $IMAGE_NAME:$VERSION_TAG .
          docker push $IMAGE_NAME:$VERSION_LATEST
          docker push $IMAGE_NAME:$VERSION_TAG
